name: somatosensory_mapping
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - jupyterlab
  - ipykernel
  - pytorch
  - seaborn
  - pip
  - pip:
      - nilearn
      - nibabel